version: '3'

services:
  db:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    networks:
      - db
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/data/db
      - ./init/:/docker-entrypoint-initdb.d/
    command: mongod
  taskserver:
    build: task
    networks:
      - db
    ports:
      - "8000:8000"
  nginx:
    build: nginx
    networks:
      - db
    ports:
      - "80:80"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    links:
      - db:mongo
    depends_on:
      - db
    networks:
      - db
    ports:
      - '8001:8081'
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456


networks:
  db:
    driver: bridge

